local M = {}

M.highlights_base = function(colors)
  return {
    -- Boolean = { fg = colors.color5 },
    -- Character = { fg = colors.color12 },
    -- CmpDocumentationBorder = { fg = colors.foreground, bg = colors.background },
    -- CmpItemAbbr = { fg = colors.foreground, bg = colors.background },
    -- CmpItemAbbrDeprecated = { fg = colors.color2, bg = colors.background },
    -- CmpItemAbbrMatch = { fg = colors.color7, bg = colors.background },
    -- CmpItemAbbrMatchFuzzy = { fg = colors.color7, bg = colors.background },
    -- CmpItemKind = { fg = colors.color4, bg = colors.background },
    -- CmpItemMenu = { fg = colors.color2, bg = colors.background },
    -- ColorColumn = { bg = colors.background },
    -- Comment = { fg = colors.color1 },
    -- Conceal = { fg = colors.color4, bg = colors.background },
    -- Conditional = { fg = colors.color2 },
    -- Constant = { fg = colors.color11 },
    -- Cursor = { fg = colors.foreground, bg = colors.cursor },
    -- CursorColumn = { bg = colors.color0 },
    -- CursorIM = { fg = colors.foreground, bg = colors.cursor },
    -- CursorLine = { bg = colors.color0 },
    -- CursorLineNr = { fg = colors.color12, bg = colors.color0},
    -- Debug = { fg = colors.color11 },
    -- Define = { fg = colors.color6 },
    -- Delimiter = { fg = colors.foreground },
    -- DiffAdd = { fg = colors.background, bg = colors.color13 },
    -- DiffChange = { fg = colors.background, bg = colors.color14 },
    -- DiffDelete = { fg = colors.background, bg = colors.color9 },
    -- Directory = { fg = colors.color4 },
    -- EndOfBuffer = { fg = colors.background },
    -- Error = { fg = colors.color11, bg = colors.background },
    -- ErrorMsg = { fg = colors.color11, bg = colors.background },
    -- Exception = { fg = colors.color6 },
    -- Float = { fg = colors.color5 },
    -- FloatBorder = { fg = colors.foreground, bg = colors.background },
    -- FoldColumn = { fg = colors.color4, bg = colors.background },
    -- Folded = { fg = colors.color4, bg = colors.background },
    -- Function = { fg = colors.color6 },
    -- Identifier = { fg = colors.color5 },
    -- Ignore = { fg = colors.color7, bg = colors.background },
    -- IncSearch = { fg = colors.foreground, bg = colors.color1 },
    -- Include = { fg = colors.color6 },
    -- Keyword = { fg = colors.color7 },
    -- Label = { fg = colors.color4 },
    -- LineNr = { fg = colors.color1, bg = colors.background },
    -- Macro = { fg = colors.color6 },
    -- MatchParen = { fg = colors.color4, bg = colors.background },
    -- ModeMsg = { fg = colors.foreground, bg = colors.background },
    -- MoreMsg = { fg = colors.color5 },
    -- MsgArea = { fg = colors.foreground, bg = colors.background },
    -- MsgSeparator = { fg = colors.foreground, bg = colors.background },
    -- NonText = { fg = colors.color1 },
    -- Normal = { fg = colors.foreground, bg = colors.background },
    -- NormalFloat = { bg = colors.color0 },
    -- NormalNC = { fg = colors.foreground, bg = colors.background },
    -- Number = { fg = colors.color5 },
    -- Operator = { fg = colors.color6 },
    -- Pmenu = { fg = colors.foreground, bg = colors.color0 },
    -- PmenuSbar = { bg = colors.background },
    -- PmenuSel = { fg = colors.background, bg = colors.color4 },
    -- PmenuThumb = { bg = colors.color2 },
    -- PreCondit = { fg = colors.color6 },
    -- PreProc = { fg = colors.color6 },
    -- Question = { fg = colors.color5 },
    -- QuickFixLine = { bg = colors.color2 },
    -- Repeat = { fg = colors.color6 },
    -- Search = { fg = colors.foreground, bg = colors.color1 },
    -- SignColumn = { bg = colors.background, fg = colors.background },
    -- Special = { fg = colors.color10 },
    -- SpecialChar = { fg = colors.color14 },
    -- SpecialComment = { fg = colors.color2 },
    -- SpecialKey = { fg = colors.color4 },
    -- SpellBad = { fg = colors.color2 },
    -- SpellCap = { fg = colors.color6 },
    -- SpellLocal = { fg = colors.color4 },
    -- SpellRare = { fg = colors.color6 },
    -- Statement = { fg = colors.color6 },
    -- StatusLine = { bg = colors.background, fg = colors.background },
    -- StatusLineNC = { bg = colors.color3, fg = colors.background },
    -- StorageClass = { fg = colors.color7 },
    -- String = { fg = colors.color12 },
    -- Structure = { fg = colors.color6 },
    -- Substitute = { fg = colors.color1, bg = colors.color6 },
    -- TabLine = { fg = colors.color2, bg = colors.background },
    -- TabLineFill = { fg = colors.foreground, bg = colors.background },
    -- TabLineSel = { fg = colors.foreground, bg = colors.background },
    -- Tag = { fg = colors.color4 },
    -- TermCursor = { fg = colors.foreground, bg = colors.cursor },
    -- TermCursorNC = { fg = colors.foreground, bg = colors.cursor },
    -- Title = { fg = colors.color4 },
    -- Todo = { fg = colors.color11, bg = colors.background },
    -- Type = { fg = colors.color5 },
    -- Typedef = { fg = colors.color6 },
    -- Variable = { fg = colors.color5 },
    -- VertSplit = { fg = colors.color0, bg = colors.background },
    -- Visual = { bg = colors.color1, fg = colors.foreground },
    -- VisualNOS = { bg = colors.background },
    -- WarningMsg = { fg = colors.color3, bg = colors.background },
    -- Whitespace = { fg = colors.color1 },
    -- WildMenu = { fg = colors.color7, bg = colors.color4 },
    -- WinSeparator = { fg = colors.color0, bg = colors.background },
    -- lCursor = { fg = colors.foreground, bg = colors.cursor },
    -- New
    Boolean = { fg = colors.color5 },
    Character = { fg = colors.color12 },
    CmpDocumentationBorder = { fg = colors.foreground, bg = colors.transparent },
    CmpItemAbbr = { fg = colors.foreground, bg = colors.transparent },
    CmpItemAbbrDeprecated = { fg = colors.color2, bg = colors.transparent },
    CmpItemAbbrMatch = { fg = colors.color7, bg = colors.transparent },
    CmpItemAbbrMatchFuzzy = { fg = colors.color7, bg = colors.transparent },
    CmpItemKind = { fg = colors.color4, bg = colors.transparent },
    CmpItemMenu = { fg = colors.color2, bg = colors.transparent },
    ColorColumn = { bg = colors.background },
    Comment = { fg = colors.color1 },
    Conceal = { fg = colors.color4, bg = colors.transparent },
    Conditional = { fg = colors.color2 },
    Constant = { fg = colors.color9 },
    Cursor = { fg = colors.foreground, bg = colors.cursor },
    CursorColumn = { bg = colors.transparent },
    CursorIM = { fg = colors.foreground, bg = colors.cursor },
    CursorLine = { bg = colors.color0 },
    CursorLineNr = { fg = colors.color12, bg = colors.color0 },
    Debug = { fg = colors.color11 },
    Define = { fg = colors.color6 },
    Delimiter = { fg = colors.foreground },
    DiffAdd = { fg = colors.foreground, bg = colors.color13 },
    DiffChange = { fg = colors.transparent, bg = colors.color14 },
    DiffDelete = { fg = colors.foreground, bg = colors.color9 },
    DiffText = { fg = colors.foreground, bg = colors.color1 },
    Directory = { fg = colors.color4 },
    EndOfBuffer = { fg = colors.background, bg = colors.transparent },
    Error = { fg = colors.color11, bg = colors.transparent },
    ErrorMsg = { fg = colors.color11, bg = colors.transparent },
    Exception = { fg = colors.color6 },
    Float = { fg = colors.color5 },
    FloatBorder = { fg = colors.foreground, bg = colors.transparent },
    FoldColumn = { fg = colors.color4, bg = colors.transparent },
    Folded = { fg = colors.color4, bg = colors.transparent },
    Function = { fg = colors.color3 },
    Identifier = { fg = colors.color7 },
    Ignore = { fg = colors.color7, bg = colors.transparent },
    IncSearch = { fg = colors.foreground, bg = colors.color3 },
    Include = { fg = colors.color6 },
    Keyword = { fg = colors.color4 },
    Label = { fg = colors.color4 },
    LineNr = { fg = colors.color1, bg = colors.transparent },
    Macro = { fg = colors.color6 },
    MatchParen = { fg = colors.color4, bg = colors.transparent },
    ModeMsg = { fg = colors.foreground, bg = colors.transparent },
    MoreMsg = { fg = colors.color5 },
    MsgArea = { fg = colors.foreground, bg = colors.transparent },
    MsgSeparator = { fg = colors.color8, bg = colors.transparent },
    NonText = { fg = colors.background },
    Normal = { fg = colors.foreground, bg = colors.transparent },
    NormalFloat = { fg = colors.foreground, bg = colors.background },
    NormalNC = { fg = colors.foreground, bg = colors.transparent },
    Number = { fg = colors.color5 },
    Operator = { fg = colors.color6 },
    Pmenu = { fg = colors.foreground, bg = colors.transparent },
    PmenuSbar = { bg = colors.transparent },
    PmenuSel = { fg = colors.transparent, bg = colors.color0 },
    PmenuThumb = { bg = colors.color2 },
    PreCondit = { fg = colors.color6 },
    PreProc = { fg = colors.color6 },
    Question = { fg = colors.color5 },
    QuickFixLine = { bg = colors.color2 },
    Repeat = { fg = colors.color6 },
    Search = { fg = colors.foreground, bg = colors.color2 },
    SignColumn = { fg = colors.transparent, bg = colors.transparent },
    Special = { fg = colors.color6 },
    SpecialChar = { fg = colors.foreground },
    SpecialComment = { fg = colors.color2 },
    SpecialKey = { fg = colors.color4 },
    SpellBad = { fg = colors.color2 },
    SpellCap = { fg = colors.color6 },
    SpellLocal = { fg = colors.color4 },
    SpellRare = { fg = colors.color6 },
    Statement = { fg = colors.color6 },
    StatusLine = { fg = colors.transparent, bg = colors.transparent },
    StatusLineNC = { fg = colors.transparent, bg = colors.transparent },
    StorageClass = { fg = colors.color7 },
    String = { fg = colors.color9 },
    Structure = { fg = colors.color6 },
    Substitute = { fg = colors.color1, bg = colors.color6 },
    Tag = { fg = colors.color4 },
    TermCursor = { fg = colors.foreground, bg = colors.cursor },
    TermCursorNC = { fg = colors.foreground, bg = colors.cursor },
    Title = { fg = colors.color4 },
    Todo = { fg = colors.color11, bg = colors.transparent },
    Type = { fg = colors.color6 },
    Typedef = { fg = colors.color6 },
    Variable = { fg = colors.color9 },
    VertSplit = { fg = colors.color4, bg = colors.transparent },
    Visual = { fg = colors.foreground, bg = colors.color5 },
    VisualNOS = { bg = colors.transparent },
    WarningMsg = { fg = colors.color3, bg = colors.transparent },
    Whitespace = { fg = colors.color8, bg = colors.background },
    WildMenu = { fg = colors.color7, bg = colors.color4 },
    WinBar = { bg = colors.transparent },
    WinBarNC = { bg = colors.transparent },
    WinSeparator = { fg = colors.color8, bg = colors.transparent },
    lCursor = { fg = colors.foreground, bg = colors.cursor },
    
    -- diff
    diffAdded = { fg = colors.color4 },
    diffRemoved = { fg = colors.color11 },
    diffChanged = { fg = colors.color5 },
    diffOldFile = { fg = colors.color5 },
    diffNewFile = { fg = colors.color5 },
    diffFile = { fg = colors.color7 },
    diffLine = { fg = colors.color1 },
    diffIndexLine = { fg = colors.color6 },

    NvimSeparator = { fg = colors.color7 },

    healthError = { fg = colors.color11 },
    healthSuccess = { fg = colors.color4 },
    healthWarning = { fg = colors.color5 },

  }
end

return M
